# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[rules]]
extensions = [
  "as",
  "aj",
  "c",
  "cc",
  "cpp",
  "cs",
  "css",
  "go",
  "gradle",
  "groovy",
  "h",
  "hh",
  "hpp",
  "java",
  "fx",
  "js",
  "cjs",
  "jsx",
  "kt",
  "kts",
  "proto",
  "scala",
  "scss",
  "ts",
  "tsx",
  "v",
  "sv",
]
style_out = "slashstar_style"
styles_in = ["slashstar_style", "doubleslash_style"]

[[rules]]
extensions = ["mbt", "rs", "zig"]
filenames = ["go.mod"]
style_out = "doubleslash_style"
styles_in = ["doubleslash_style", "slashstar_style"]

[[rules]]
extensions = [
  "pl",
  "pm",
  "properties",
  "py",
  "pyi",
  "rb",
  "sh",
  "toml",
  "yaml",
  "yml",
]
filenames = [
  ".editorconfig",
  "CMakeLists.txt",
  "Containerfile",
  "Dockerfile",
  "Makefile",
]
style_out = "script_style"

[[rules]]
extensions = ["adb", "ads", "e", "sql"]
style_out = "doubledashes_style"

[[rules]]
extensions = [
  "fml",
  "dtd",
  "gsp",
  "htm",
  "html",
  "jspx",
  "kml",
  "mxml",
  "pom",
  "svelte",
  "tagx",
  "tld",
  "vue",
  "wsdl",
  "xhtml",
  "xml",
  "xsd",
  "xsl",
  "xslt",
]
style_out = "xml_style"
styles_in = ["xml_style", "xml_per_line"]

[[rules]]
extensions = ["asm", "clj", "cljs", "el"]
style_out = "semicolon_style"

[[rules]]
extensions = ["f"]
style_out = "exclamation_style"

[[rules]]
extensions = ["erl", "hrl"]
style_out = "percent3_style"

[[rules]]
extensions = ["cls", "sty", "tex"]
style_out = "percent_style"

[[rules]]
extensions = ["bas", "vba"]
style_out = "apostrophe_style"

[[rules]]
extensions = ["bat", "cmd"]
style_out = "batch"

[[rules]]
extensions = ["pas"]
style_out = "bracesstar_style"

[[rules]]
extensions = ["vm"]
style_out = "sharpstar_style"

[[rules]]
extensions = ["mustache"]
style_out = "mustache_style"

[[rules]]
extensions = ["mv"]
style_out = "mvel_style"

[[rules]]
extensions = ["ftl"]
style_out = "ftl"
styles_in = ["ftl", "ftl_alt"]

[[rules]]
extensions = ["jsp"]
style_out = "dynascript_style"

[[rules]]
extensions = ["cfc", "cfm"]
style_out = "dynascript3_style"

[[rules]]
extensions = ["asp"]
style_out = "asp"

[[rules]]
extensions = ["php"]
style_out = "slashstar_style"
styles_in = ["slashstar_style", "doubleslash_style"]

[[rules]]
extensions = ["lua"]
style_out = "lua"

[[rules]]
extensions = ["adoc"]
style_out = "asciidoc_style"

[[rules]]
extensions = ["pkl"]
filenames = ["PklProject"]
style_out = "line_block_style"
styles_in = ["line_block_style", "doubleslash_style"]

[[rules]]
extensions = ["haml", "scaml"]
style_out = "haml_style"

[[rules]]
extensions = ["apt"]
style_out = "doubletilde_style"
