# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[styles.doubleslash_style]
kind = "line"
prefix = "// "

[styles.tripleslash_style]
kind = "line"
prefix = "/// "

[styles.script_style]
kind = "line"
prefix = "# "

[styles.doubledashes_style]
kind = "line"
prefix = "-- "

[styles.percent_style]
kind = "line"
prefix = "% "

[styles.percent3_style]
kind = "line"
prefix = "%%% "

[styles.semicolon_style]
kind = "line"
prefix = "; "

[styles.apostrophe_style]
kind = "line"
prefix = "' "

[styles.exclamation_style]
kind = "line"
prefix = "! "

[styles.exclamation3_style]
kind = "line"
prefix = "!!! "

[styles.doubletilde_style]
kind = "line"
prefix = "~~ "

[styles.batch]
kind = "line"
prefix = "@REM "

[styles.haml_style]
kind = "line"
prefix = "-# "

[styles.xml_per_line]
kind = "line"
prefix = "<!-- "
suffix = " -->"
pad_lines = true

[styles.slashstar_style]
kind = "block"
start = "/*"
prefix = " * "
end = " */"

[styles.javadoc_style]
kind = "block"
start = "/**"
prefix = " * "
end = " */"

[styles.xml_style]
kind = "block"
start = "<!--"
prefix = "    "
end = "-->"

[styles.lua]
kind = "block"
start = "--[["
prefix = "    "
end = "]]"

[styles.bracesstar_style]
kind = "block"
start = "{*"
prefix = " * "
end = " *}"

[styles.sharpstar_style]
kind = "block"
start = "#*"
prefix = " * "
end = " *#"

[styles.mustache_style]
kind = "block"
start = "{{!"
prefix = "    "
end = "}}"

[styles.mvel_style]
kind = "block"
start = "@comment{"
prefix = "  "
end = "}"

[styles.ftl]
kind = "block"
start = "<#--"
prefix = "    "
end = "-->"

[styles.ftl_alt]
kind = "block"
start = "[#--"
prefix = "    "
end = "--]"

[styles.dynascript_style]
kind = "block"
start = "<%--"
prefix = "    "
end = "--%>"

[styles.dynascript3_style]
kind = "block"
start = "<!---"
prefix = "    "
end = "--->"

[styles.asp]
kind = "block"
start = "<%"
prefix = "' "
end = "%>"

[styles.line_block_style]
kind = "block"
start = "//===----------------------------------------------------------------------===//"
prefix = "// "
end = "//===----------------------------------------------------------------------===//"

[styles.asciidoc_style]
kind = "block"
start = "////"
prefix = "// "
end = "////"
