# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[styles.slash_line]
kind = "line"
prefix = "// "

[styles.triple_slash_line]
kind = "line"
prefix = "/// "

[styles.hash_line]
kind = "line"
prefix = "# "

[styles.dash_line]
kind = "line"
prefix = "-- "

[styles.percent_line]
kind = "line"
prefix = "% "

[styles.percent3_line]
kind = "line"
prefix = "%%% "

[styles.semicolon_line]
kind = "line"
prefix = "; "

[styles.apostrophe_line]
kind = "line"
prefix = "' "

[styles.bang_line]
kind = "line"
prefix = "! "

[styles.bang3_line]
kind = "line"
prefix = "!!! "

[styles.tilde2_line]
kind = "line"
prefix = "~~ "

[styles.rem_line]
kind = "line"
prefix = "@REM "

[styles.haml_line]
kind = "line"
prefix = "-# "

[styles.xml_line]
kind = "line"
pad_lines = true
prefix = "<!-- "
suffix = " -->"

[styles.slash_block]
end = " */"
kind = "block"
prefix = " * "
start = "/*"

[styles.javadoc_block]
end = " */"
kind = "block"
prefix = " * "
start = "/**"

[styles.xml_block]
end = "-->"
kind = "block"
prefix = "    "
start = "<!--"

[styles.lua_block]
end = "]]"
kind = "block"
prefix = "    "
start = "--[["

[styles.brace_star_block]
end = " *}"
kind = "block"
prefix = " * "
start = "{*"

[styles.hash_star_block]
end = " *#"
kind = "block"
prefix = " * "
start = "#*"

[styles.mustache_block]
end = "}}"
kind = "block"
prefix = "    "
start = "{{!"

[styles.mvel_block]
end = "}"
kind = "block"
prefix = "  "
start = "@comment{"

[styles.freemarker_block]
end = "-->"
kind = "block"
prefix = "    "
start = "<#--"

[styles.freemarker_alt_block]
end = "--]"
kind = "block"
prefix = "    "
start = "[#--"

[styles.jsp_block]
end = "--%>"
kind = "block"
prefix = "    "
start = "<%--"

[styles.coldfusion_block]
end = "--->"
kind = "block"
prefix = "    "
start = "<!---"

[styles.asp_block]
end = "%>"
kind = "block"
prefix = "' "
start = "<%"

[styles.swift_banner]
end = "//===----------------------------------------------------------------------===//"
kind = "block"
prefix = "// "
start = "//===----------------------------------------------------------------------===//"

[styles.asciidoc_block]
end = "////"
kind = "block"
prefix = "// "
start = "////"
